# live_runner_zerodha_paper.py
# ------------------------------------------------------------
# Strategy runner for Zerodha with PAPER/LIVE execution modes
# - Uses your test_signals.py pipeline
# - Polls underlying candles (5m by default)
# - Generates signals on latest completed candle
# - Maps ATM option (CE for LONG, PE for SHORT)
# - In PAPER mode: simulates option trade with T1 -> BE -> EOD
# - In LIVE mode: places real entry/exit orders with safety guards
# - Logs signals, trades, and errors to CSV
#
# IMPORTANT:
# 1) PAPER mode places NO orders.
# 2) LIVE mode places REAL ORDERS (requires explicit confirmation flag).
# 3) Keep KITE_API_KEY in env and access_token.txt refreshed daily.
# 4) Edit the CONFIG section below as needed.
# ------------------------------------------------------------

from __future__ import annotations

import os
import sys
import time
import math
import inspect
import traceback
import argparse
from dataclasses import asdict, is_dataclass
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple, Set

import pandas as pd
from pathlib import Path
from dotenv import load_dotenv

# Add project root to sys.path so 'core' module can be found
proj_root = Path(__file__).resolve().parent.parent
if str(proj_root) not in sys.path:
    sys.path.insert(0, str(proj_root))

load_dotenv(proj_root / ".env")

try:
    from kiteconnect import KiteConnect
except Exception:
    print(" kiteconnect not installed. Run: pip install kiteconnect")
    raise


# ============================================================
# CONFIG
# ============================================================
# Use your app key directly (same one used in generate_kite_token.py)
DEFAULT_API_KEY = "sudneg6y3zb2gxz7"

# Token file generated by generate_kite_token.py
ACCESS_TOKEN_FILE = proj_root / "broker/access_token.txt"

# Prefer env only if explicitly set, otherwise fallback to default
API_KEY = os.getenv("KITE_API_KEY", "").strip() or DEFAULT_API_KEY


def load_access_token() -> str:
    """
    Prefer file token (generated by generate_kite_token.py),
    fallback to env var. Strips whitespace/newline.
    """
    # 1) Prefer file first (safer in your workflow)
    if os.path.exists(ACCESS_TOKEN_FILE):
        with open(ACCESS_TOKEN_FILE, "r", encoding="utf-8") as f:
            token = f.read().strip()
        if token:
            print("DEBUG [auth] token source: file")
            return token

    # 2) Fallback to env var
    token = os.getenv("KITE_ACCESS_TOKEN", "").strip()
    if token:
        print("DEBUG [auth] token source: env")
        return token

    raise FileNotFoundError(
        f"Access token not found in {ACCESS_TOKEN_FILE} or KITE_ACCESS_TOKEN env var. "
        f"Run generate_kite_token.py first."
    )


# Backward compatibility for old code paths in this file
# (so existing kite.set_access_token(ACCESS_TOKEN) lines won't crash)
ACCESS_TOKEN = load_access_token()


def get_kite() -> KiteConnect:
    """
    Create and validate Kite client.
    """
    print("DEBUG [auth] CWD:", os.getcwd())
    print("DEBUG [auth] API_KEY repr:", repr(API_KEY))
    print("DEBUG [auth] token repr :", repr(ACCESS_TOKEN))
    print("DEBUG [auth] token len  :", len(ACCESS_TOKEN))

    kite = KiteConnect(api_key=API_KEY)
    kite.set_access_token(ACCESS_TOKEN)

    profile = kite.profile()  # validate token
    print(" [auth] Kite authenticated")
    print("   User ID   :", profile.get("user_id"))
    print("   User Name :", profile.get("user_name"))
    return kite



# Underlying signal source
# IMPORTANT: strategy signals are generated from FUTURES candles.
UNDERLYING_EXCHANGE = "NFO"
UNDERLYING_SIGNAL_MODE = "FUT"   # "FUT" or "SPOT"
UNDERLYING_SYMBOL = "NIFTY 50"   # used only when UNDERLYING_SIGNAL_MODE == "SPOT"
UNDERLYING_FUT_NAME = "NIFTY"    # name in NFO futures master for near-month lookup

# Options mapping
OPTION_EXCHANGE = "NFO"
OPTION_UNDERLYING_NAME = "NIFTY"  # name field in NFO instruments master (NIFTY / BANKNIFTY etc.)

# Strategy timeframe
CANDLE_INTERVAL = "5minute"       # must match your strategy prep/generation assumptions
POLL_EVERY_SECONDS = 20           # polling cycle; keep moderate to avoid rate bursts

# Signal generation params (must match your strategy defaults / experiments)
TARGET1_POINTS = 40.0
TOUCH_TOLERANCE = 5.0
BREAK_CONFIRMATION = 0.0
SL_BUFFER_POINTS = 12.0
MIN_BODY_POINTS = 0.0
ALLOW_LONG_PP_SIGNAL = False
ALLOW_SHORT_PP_SIGNAL = False
SIGNAL_ENTRY_CUTOFF_HHMM: Optional[int] = None
PP_ENTRY_CUTOFF_HHMM: Optional[int] = None
MAX_CANDLE_RANGE_POINTS: Optional[float] = None
MAX_SL_DISTANCE_POINTS: Optional[float] = None

# Paper option simulation assumptions
LOTS = 2
SLIPPAGE_PER_SIDE_RUPEES = 0.50
CHARGES_PER_LOT_ROUNDTRIP = 60.00

# Timing / risk controls
MAX_TRADES_PER_DAY = 6
ALLOW_ENTRY_FROM = "09:20"        # HH:MM local time
ALLOW_ENTRY_TILL = "14:45"        # no new entry after this
FORCE_EXIT_TIME = "15:20"         # paper exits any open trade by this time
MARKET_START = "09:15"
MARKET_END = "15:30"

# Files
LOG_DIR = proj_root
SIGNALS_LOG_CSV = LOG_DIR / "live_paper_signals_log.csv"
TRADES_LOG_CSV = LOG_DIR / "live_paper_option_trades_log.csv"
ERROR_LOG_CSV = LOG_DIR / "live_paper_errors_log.csv"
STATE_SNAPSHOT_JSON = LOG_DIR / "live_paper_state_snapshot.json"
STOP_FILE = LOG_DIR / "STOP_TRADING.txt"

# Safeguards
PRINT_HEARTBEAT_EVERY_LOOPS = 6   # print heartbeat every N loops
ENABLE_DEDUP_BY_SIGNAL_TIME = True
ENABLE_DEDUP_BY_TRADEKEY = True

# Execution mode
# PAPER: no real orders (default)
# LIVE: places real buy/sell orders in Zerodha
EXECUTION_MODE_DEFAULT = "PAPER"
LIVE_PRODUCT = os.getenv("LIVE_PRODUCT", "MIS").strip().upper()  # MIS or NRML
LIVE_CONFIRM_TEXT = "LIVE_TRADING_ACK"
MAX_DAILY_LOSS_RUPEES = float(os.getenv("MAX_DAILY_LOSS_RUPEES", "3000"))
LIVE_ORDER_TIMEOUT_SEC = int(os.getenv("LIVE_ORDER_TIMEOUT_SEC", "20"))


def _parse_runtime_args(default_profile: str = "NIFTY") -> argparse.Namespace:
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--profile", choices=["nifty", "banknifty"])
    parser.add_argument("--mode", choices=["paper", "live"], default=os.getenv("EXECUTION_MODE", EXECUTION_MODE_DEFAULT).lower())
    parser.add_argument("--confirm", default="", help=f"Required for live mode: --confirm {LIVE_CONFIRM_TEXT}")
    args, _ = parser.parse_known_args()
    val = (args.profile or os.getenv("STRATEGY_PROFILE", default_profile)).strip().upper()
    args.profile = "BANKNIFTY" if "BANK" in val else "NIFTY"
    args.mode = str(args.mode).strip().upper()
    return args


def apply_strategy_profile(profile: str) -> None:
    global UNDERLYING_EXCHANGE, UNDERLYING_SIGNAL_MODE, UNDERLYING_SYMBOL, UNDERLYING_FUT_NAME
    global OPTION_UNDERLYING_NAME, TARGET1_POINTS
    global ALLOW_LONG_PP_SIGNAL, ALLOW_SHORT_PP_SIGNAL
    global MIN_BODY_POINTS, SIGNAL_ENTRY_CUTOFF_HHMM, PP_ENTRY_CUTOFF_HHMM
    global MAX_CANDLE_RANGE_POINTS, MAX_SL_DISTANCE_POINTS
    global ALLOW_ENTRY_TILL
    global SIGNALS_LOG_CSV, TRADES_LOG_CSV, ERROR_LOG_CSV, STATE_SNAPSHOT_JSON, STOP_FILE

    p = profile.strip().upper()
    if p == "BANKNIFTY":
        UNDERLYING_EXCHANGE = "NFO"
        UNDERLYING_SIGNAL_MODE = "FUT"
        UNDERLYING_SYMBOL = "NIFTY BANK"
        UNDERLYING_FUT_NAME = "BANKNIFTY"
        OPTION_UNDERLYING_NAME = "BANKNIFTY"
        TARGET1_POINTS = 80.0
        ALLOW_LONG_PP_SIGNAL = True
        ALLOW_SHORT_PP_SIGNAL = True
        MIN_BODY_POINTS = 10.0
        SIGNAL_ENTRY_CUTOFF_HHMM = 1330
        PP_ENTRY_CUTOFF_HHMM = 1030
        MAX_CANDLE_RANGE_POINTS = 120.0
        MAX_SL_DISTANCE_POINTS = 60.0
        ALLOW_ENTRY_TILL = "13:30"
        SIGNALS_LOG_CSV = LOG_DIR / "live_paper_signals_log_banknifty.csv"
        TRADES_LOG_CSV = LOG_DIR / "live_paper_option_trades_log_banknifty.csv"
        ERROR_LOG_CSV = LOG_DIR / "live_paper_errors_log_banknifty.csv"
        STATE_SNAPSHOT_JSON = LOG_DIR / "live_paper_state_snapshot_banknifty.json"
        STOP_FILE = LOG_DIR / "STOP_TRADING_BANKNIFTY.txt"
    else:
        UNDERLYING_EXCHANGE = "NFO"
        UNDERLYING_SIGNAL_MODE = "FUT"
        UNDERLYING_SYMBOL = "NIFTY 50"
        UNDERLYING_FUT_NAME = "NIFTY"
        OPTION_UNDERLYING_NAME = "NIFTY"
        TARGET1_POINTS = 40.0
        ALLOW_LONG_PP_SIGNAL = False
        ALLOW_SHORT_PP_SIGNAL = False
        MIN_BODY_POINTS = 0.0
        SIGNAL_ENTRY_CUTOFF_HHMM = None
        PP_ENTRY_CUTOFF_HHMM = None
        MAX_CANDLE_RANGE_POINTS = None
        MAX_SL_DISTANCE_POINTS = None
        ALLOW_ENTRY_TILL = "14:45"
        SIGNALS_LOG_CSV = LOG_DIR / "live_paper_signals_log.csv"
        TRADES_LOG_CSV = LOG_DIR / "live_paper_option_trades_log.csv"
        ERROR_LOG_CSV = LOG_DIR / "live_paper_errors_log.csv"
        STATE_SNAPSHOT_JSON = LOG_DIR / "live_paper_state_snapshot.json"
        STOP_FILE = LOG_DIR / "STOP_TRADING.txt"


# ============================================================
# Utilities
# ============================================================
def _now_local() -> pd.Timestamp:
    # Use local machine time; your signals/candles are IST
    return pd.Timestamp.now(tz="Asia/Kolkata")


def _parse_hhmm(hhmm: str) -> Tuple[int, int]:
    h, m = hhmm.split(":")
    return int(h), int(m)


def _today_time(hhmm: str, ref: Optional[pd.Timestamp] = None) -> pd.Timestamp:
    ref = ref or _now_local()
    h, m = _parse_hhmm(hhmm)
    return ref.normalize() + pd.Timedelta(hours=h, minutes=m)


def in_time_window(now: pd.Timestamp, start_hhmm: str, end_hhmm: str) -> bool:
    start = _today_time(start_hhmm, now)
    end = _today_time(end_hhmm, now)
    return start <= now <= end


def append_csv_row(path: str, row: Dict[str, Any]) -> None:
    df = pd.DataFrame([row])
    header = not os.path.exists(path)
    df.to_csv(path, mode="a", header=header, index=False)


def log_error(where: str, err: Exception | str, extra: Optional[Dict[str, Any]] = None) -> None:
    payload = {
        "ts": str(_now_local()),
        "where": where,
        "error": str(err),
    }
    if extra:
        payload.update(extra)
    append_csv_row(ERROR_LOG_CSV, payload)
    print(f" [{where}] {err}")


def round_to_step(x: float, step: int) -> int:
    return int(round(float(x) / step) * step)


def strike_step_for_underlying(name: str) -> int:
    n = name.upper()
    if "BANK" in n:
        return 100
    if "FIN" in n:
        return 50
    return 50


def option_type_for_side(side: str) -> str:
    # Buy options only
    return "CE" if str(side).upper() == "LONG" else "PE"


def safe_float(x, default=None):
    try:
        if x is None:
            return default
        return float(x)
    except Exception:
        return default


# ============================================================
# Signal compatibility helpers
# ============================================================
def _sig_get(signal, *names):
    for name in names:
        if hasattr(signal, name):
            v = getattr(signal, name)
            if v is not None:
                return v
    if isinstance(signal, dict):
        for name in names:
            if name in signal and signal[name] is not None:
                return signal[name]
    if is_dataclass(signal):
        d = asdict(signal)
        for name in names:
            if name in d and d[name] is not None:
                return d[name]
    available = list(getattr(signal, "__dict__", {}).keys()) if hasattr(signal, "__dict__") else []
    raise AttributeError(f"Signal missing fields {names}. Available: {available}")


def sig_time(signal) -> pd.Timestamp:
    return pd.to_datetime(_sig_get(signal, "entry_time", "ts", "timestamp", "time", "datetime"), errors="coerce")


def sig_side(signal) -> str:
    return str(_sig_get(signal, "side", "direction", "signal_type")).upper().strip()


def sig_entry(signal) -> float:
    return float(_sig_get(signal, "entry", "fut_entry", "entry_price", "trigger_price", "price", "entry"))


def sig_sl(signal) -> float:
    return float(_sig_get(signal, "sl", "fut_sl", "sl_price", "stop_loss", "sl"))


def sig_tp(signal) -> Optional[float]:
    try:
        return float(_sig_get(signal, "tp", "fut_tp", "target", "target_price"))
    except Exception:
        return None


def sig_level_tag(signal) -> str:
    for name in ["level_tag", "level_name", "pivot_tag", "tag"]:
        try:
            return str(_sig_get(signal, name))
        except Exception:
            continue
    return ""


def sig_level_price(signal) -> Optional[float]:
    for name in ["level_price", "level_value", "pivot_price", "level"]:
        try:
            return float(_sig_get(signal, name))
        except Exception:
            continue
    return None


# ============================================================
# Zerodha auth / instruments
# ============================================================
def read_access_token_fallback() -> str:
    if ACCESS_TOKEN:
        return ACCESS_TOKEN
    if os.path.exists(ACCESS_TOKEN_FILE):
        with open(ACCESS_TOKEN_FILE, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""


def make_kite() -> KiteConnect:
    api_key = API_KEY
    token = read_access_token_fallback()

    if not api_key:
        raise RuntimeError("Missing KITE_API_KEY env var.")
    if not token:
        raise RuntimeError("Missing access token (env KITE_ACCESS_TOKEN or access_token.txt).")

    kite = KiteConnect(api_key=api_key)
    kite.set_access_token(token)

    profile = kite.profile()  # auth check
    uname = profile.get("user_name") or profile.get("user_id") or "Unknown"
    print(f"Kite auth OK  | {uname}")
    return kite


def get_order_snapshot(kite: KiteConnect, order_id: str) -> Optional[dict]:
    orders = kite.orders()
    for o in reversed(orders):
        if str(o.get("order_id")) == str(order_id):
            return o
    return None


def wait_for_order_status(
    kite: KiteConnect,
    order_id: str,
    statuses: Set[str],
    timeout_sec: int,
    poll_sec: float = 1.0,
) -> Optional[dict]:
    start = time.time()
    target = {str(s).upper() for s in statuses}
    while time.time() - start <= timeout_sec:
        snap = get_order_snapshot(kite, order_id)
        if snap and str(snap.get("status", "")).upper() in target:
            return snap
        time.sleep(poll_sec)
    return get_order_snapshot(kite, order_id)


def _order_avg_fill_price(order_snap: Optional[dict], fallback: float) -> float:
    if not order_snap:
        return float(fallback)
    for k in ("average_price", "avg_price", "price"):
        v = safe_float(order_snap.get(k))
        if v is not None and v > 0:
            return float(v)
    return float(fallback)


def place_market_order(
    kite: KiteConnect,
    exchange: str,
    tradingsymbol: str,
    tx_type: str,
    qty: int,
    product: str,
) -> str:
    oid = kite.place_order(
        variety=kite.VARIETY_REGULAR,
        exchange=exchange,
        tradingsymbol=tradingsymbol,
        transaction_type=tx_type,
        quantity=int(qty),
        product=product,
        order_type=kite.ORDER_TYPE_MARKET,
        validity=kite.VALIDITY_DAY,
    )
    return str(oid)


def load_instruments(kite: KiteConnect) -> Tuple[pd.DataFrame, pd.DataFrame]:
    print("Loading instruments master (NSE + NFO)...")
    nse_df = pd.DataFrame(kite.instruments("NSE"))
    nfo_df = pd.DataFrame(kite.instruments("NFO"))
    if nse_df.empty:
        raise RuntimeError("NSE instruments empty")
    if nfo_df.empty:
        raise RuntimeError("NFO instruments empty")
    print(f"NSE instruments: {len(nse_df)} | NFO instruments: {len(nfo_df)}")
    return nse_df, nfo_df


def get_underlying_token(
    nse_df: pd.DataFrame,
    nfo_df: pd.DataFrame,
    symbol: str,
    fut_name: str,
    signal_mode: str = "FUT",
) -> Tuple[int, str]:
    mode = str(signal_mode).upper().strip()

    if mode == "SPOT":
        # For index spot, Zerodha instruments('NSE') usually has tradingsymbol = "NIFTY 50"
        x = nse_df[nse_df["tradingsymbol"].astype(str).str.upper() == symbol.upper()].copy()
        if x.empty:
            x = nse_df[nse_df["tradingsymbol"].astype(str).str.upper().str.contains(symbol.upper(), na=False)].copy()
        if x.empty:
            raise RuntimeError(f"Underlying symbol not found in NSE instruments: {symbol}")
        row = x.iloc[0]
        return int(row["instrument_token"]), str(row.get("tradingsymbol", symbol))

    # FUT mode: nearest non-expired index future
    fut = nfo_df.copy()
    for col in ["segment", "name", "expiry", "instrument_token", "tradingsymbol"]:
        if col not in fut.columns:
            raise RuntimeError(f"NFO instruments missing required column: {col}")

    fut = fut[fut["segment"].astype(str).str.upper() == "NFO-FUT"].copy()
    fut = fut[fut["name"].astype(str).str.upper() == str(fut_name).upper()].copy()
    fut["expiry"] = pd.to_datetime(fut["expiry"], errors="coerce")
    fut = fut.dropna(subset=["expiry"]).copy()

    today = _now_local().date()
    fut = fut[fut["expiry"].dt.date >= today].copy()
    if fut.empty:
        raise RuntimeError(f"No active futures found for {fut_name}")

    fut = fut.sort_values(["expiry", "tradingsymbol"]).reset_index(drop=True)
    row = fut.iloc[0]
    return int(row["instrument_token"]), str(row["tradingsymbol"])


def _debug_latest_candle_no_signal(prepared_df: pd.DataFrame, latest_ts: pd.Timestamp) -> None:
    try:
        if latest_ts not in prepared_df.index:
            print(f"[debug] no-row-for-latest-candle ts={latest_ts}")
            return

        row_any = prepared_df.loc[latest_ts]
        row = row_any.iloc[-1] if isinstance(row_any, pd.DataFrame) else row_any

        o = float(row["open"])
        h = float(row["high"])
        l = float(row["low"])
        c = float(row["close"])
        body = abs(c - o)
        rng = abs(h - l)
        hhmm = int(latest_ts.hour) * 100 + int(latest_ts.minute)
        cutoff = SIGNAL_ENTRY_CUTOFF_HHMM if SIGNAL_ENTRY_CUTOFF_HHMM is not None else 1400

        print(
            f"[debug] latest-candle ts={latest_ts} ohlc=({o:.2f},{h:.2f},{l:.2f},{c:.2f}) "
            f"body={body:.2f} range={rng:.2f} hhmm={hhmm} cutoff={cutoff}"
        )

        reasons: List[str] = []
        if hhmm > cutoff:
            reasons.append(f"entry-cutoff-fail({hhmm}>{cutoff})")
        if body < float(MIN_BODY_POINTS):
            reasons.append(f"min-body-fail({body:.2f}<{float(MIN_BODY_POINTS):.2f})")
        if MAX_CANDLE_RANGE_POINTS is not None and rng > float(MAX_CANDLE_RANGE_POINTS):
            reasons.append(f"range-fail({rng:.2f}>{float(MAX_CANDLE_RANGE_POINTS):.2f})")

        if reasons:
            print("[debug] hard-filters:", ", ".join(reasons))

        levels = []
        for nm in ["PP", "R1", "R2", "S1", "S2"]:
            lv = row.get(nm)
            if pd.notna(lv):
                levels.append((nm, float(lv)))

        checks: List[str] = []
        for nm, lv in levels:
            touched = (l - TOUCH_TOLERANCE) <= lv <= (h + TOUCH_TOLERANCE)
            long_ok = touched and (c > (lv + BREAK_CONFIRMATION)) and (c >= o)
            short_ok = touched and (c < (lv - BREAK_CONFIRMATION)) and (c <= o)
            enabled = (
                (nm == "PP" and (ALLOW_LONG_PP_SIGNAL or ALLOW_SHORT_PP_SIGNAL))
                or (nm in {"R1", "R2"})
                or (nm == "S1")
            )
            checks.append(
                f"{nm}:touch={touched} long={long_ok} short={short_ok} enabled={enabled} lv={lv:.2f}"
            )

        print("[debug] level-checks | " + " | ".join(checks))
    except Exception as e:
        print(f"[debug] failed-to-explain-no-signal: {e}")


# ============================================================
# Candle fetch
# ============================================================
def fetch_underlying_intraday(
    kite: KiteConnect,
    underlying_token: int,
    interval: str,
    day: Optional[pd.Timestamp] = None,
) -> pd.DataFrame:
    now = _now_local()
    day = day or now
    start = day.normalize() + pd.Timedelta(hours=9, minutes=0)
    end = now  # current time
    candles = kite.historical_data(
        instrument_token=underlying_token,
        from_date=start.to_pydatetime(),
        to_date=end.to_pydatetime(),
        interval=interval,
        continuous=False,
        oi=False,
    )
    df = pd.DataFrame(candles)
    if not df.empty and "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        # normalize expected names for test_signals pipeline
        df = df.rename(columns={"date": "datetime"})
    return df


def fetch_option_intraday_from_signal_time(
    kite: KiteConnect,
    option_token: int,
    signal_time: pd.Timestamp,
    interval: str = "5minute",
) -> pd.DataFrame:
    start = signal_time.normalize()
    end = _now_local()
    candles = kite.historical_data(
        instrument_token=option_token,
        from_date=start.to_pydatetime(),
        to_date=end.to_pydatetime(),
        interval=interval,
        continuous=False,
        oi=False,
    )
    df = pd.DataFrame(candles)
    if not df.empty and "date" in df.columns:
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
    return df


# ============================================================
# Strategy integration via monkey-patch capture of test_signals.py
# ============================================================
def run_strategy_and_capture(df_raw: pd.DataFrame) -> Tuple[pd.DataFrame, List[Any]]:
    """
    Calls your test_signals.main() but monkey-patches prepare_df and generate_signals
    so we can inject our live df and capture prepared+signals.

    Assumes:
      - test_signals.py exports prepare_df, generate_signals, main
      - prepare_df(df) and generate_signals(df, ...)
      - main() internally reads data & calls these functions
    """
    import core.test_signals as mod

    captured: Dict[str, Any] = {
        "prepared": None,
        "signals": None,
    }

    orig_prepare_df = mod.prepare_df
    orig_generate_signals = mod.generate_signals

    # Save original pd.read_csv if main() reads CSV internally
    orig_read_csv = None
    if hasattr(mod, "pd") and hasattr(mod.pd, "read_csv"):
        orig_read_csv = mod.pd.read_csv

    # Wrapper: ignore whatever main loaded, use our live df_raw
    def wrapped_prepare_df(_df_ignored, *args, **kwargs):
        out = orig_prepare_df(df_raw.copy(), *args, **kwargs)
        captured["prepared"] = out
        return out

    # Wrapper: inject our generation params and capture signals
    def wrapped_generate_signals(df, *args, **kwargs):
        # Force runtime profile config even if test_signals.main() passes hardcoded params.
        kwargs = dict(kwargs)
        kwargs["target_points"] = TARGET1_POINTS
        kwargs["touch_tolerance"] = TOUCH_TOLERANCE
        kwargs["break_confirmation"] = BREAK_CONFIRMATION
        kwargs["sl_buffer_points"] = SL_BUFFER_POINTS
        kwargs["min_body_points"] = MIN_BODY_POINTS
        kwargs["allow_long_pp"] = ALLOW_LONG_PP_SIGNAL
        kwargs["allow_short_pp"] = ALLOW_SHORT_PP_SIGNAL
        kwargs["entry_cutoff_hhmm"] = SIGNAL_ENTRY_CUTOFF_HHMM
        kwargs["pp_entry_cutoff_hhmm"] = PP_ENTRY_CUTOFF_HHMM
        kwargs["max_candle_range_points"] = MAX_CANDLE_RANGE_POINTS
        kwargs["max_sl_distance_points"] = MAX_SL_DISTANCE_POINTS

        out = orig_generate_signals(df, *args, **kwargs)
        captured["signals"] = out
        return out

    # Optional patch: if main() reads CSV, return our df
    def wrapped_read_csv(*args, **kwargs):
        return df_raw.copy()

    try:
        mod.prepare_df = wrapped_prepare_df
        mod.generate_signals = wrapped_generate_signals
        if orig_read_csv is not None:
            mod.pd.read_csv = wrapped_read_csv

        # main() may print a lot; that's okay for debugging
        mod.main()

    finally:
        mod.prepare_df = orig_prepare_df
        mod.generate_signals = orig_generate_signals
        if orig_read_csv is not None:
            mod.pd.read_csv = orig_read_csv

    prepared: pd.DataFrame = captured["prepared"] # type: ignore
    signals: List[Any] = captured["signals"] # type: ignore

    if prepared is None:
        raise RuntimeError("Strategy run failed: prepare_df output was not captured.")
    if not isinstance(signals, list):
        raise RuntimeError("Strategy run failed: generate_signals output was not captured as list.")

    return prepared, signals


# ============================================================
# Option contract mapping
# ============================================================
def find_option_contract(
    nfo_df: pd.DataFrame,
    signal_time: pd.Timestamp,
    underlying_name: str,
    side: str,
    fut_entry_price: float,
) -> Tuple[Optional[pd.Series], Optional[str]]:
    if pd.isna(signal_time):
        return None, "Invalid signal_time"

    opt_type = option_type_for_side(side)
    step = strike_step_for_underlying(underlying_name)
    atm_strike = round_to_step(fut_entry_price, step)

    df = nfo_df.copy()
    required = {"tradingsymbol", "instrument_token", "name", "strike", "instrument_type", "expiry", "lot_size"}
    missing = [c for c in required if c not in df.columns]
    if missing:
        return None, f"NFO instruments missing columns: {missing}"

    df = df[df["name"].astype(str).str.upper() == underlying_name.upper()].copy()
    df = df[df["instrument_type"].astype(str).str.upper() == opt_type].copy()
    df["strike"] = pd.to_numeric(df["strike"], errors="coerce")
    df = df[df["strike"] == float(atm_strike)].copy()

    if df.empty:
        return None, f"No {underlying_name} {opt_type} at strike {atm_strike}"

    df["expiry"] = pd.to_datetime(df["expiry"], errors="coerce")
    df = df.dropna(subset=["expiry"]).copy()

    trade_date = signal_time.date()
    df = df[df["expiry"].dt.date >= trade_date].copy()
    if df.empty:
        return None, f"No non-expired contract for {underlying_name} {opt_type} {atm_strike}"

    df = df.sort_values(["expiry", "tradingsymbol"]).reset_index(drop=True)
    return df.iloc[0], None


# ============================================================
# Paper trade state machine (option)
# ============================================================
def open_paper_trade_from_signal(
    signal,
    contract_row: pd.Series,
    option_candles: pd.DataFrame,
    execution_mode: str = "PAPER",
    forced_entry_price: Optional[float] = None,
    forced_entry_time: Optional[pd.Timestamp] = None,
) -> Dict[str, Any]:
    """
    Open paper trade using first option candle >= signal_time.
    """
    st = sig_time(signal)
    side = sig_side(signal)
    fut_entry = sig_entry(signal)
    fut_sl = sig_sl(signal)
    fut_tp = sig_tp(signal)
    level_tag = sig_level_tag(signal)
    level_price = sig_level_price(signal)

    if option_candles.empty or "date" not in option_candles.columns:
        raise RuntimeError("No option candle data for opening trade.")

    df = option_candles.copy()
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    row_df = df[df["date"] >= st].copy()
    if row_df.empty:
        raise RuntimeError("No option candle at/after signal time for entry.")
    entry_candle = row_df.iloc[0]
    opt_entry_time = pd.to_datetime(entry_candle["date"], errors="coerce")
    opt_entry_price = float(entry_candle["close"])
    if forced_entry_time is not None and not pd.isna(forced_entry_time):
        opt_entry_time = pd.to_datetime(forced_entry_time, errors="coerce")
    if forced_entry_price is not None and float(forced_entry_price) > 0:
        opt_entry_price = float(forced_entry_price)

    # Proxy T1/SL from futures target points
    # Can be refined later (delta/vega model or exact exit timestamp mapping)
    assumed_delta = 0.50
    opt_t1_points = max(1.0, TARGET1_POINTS * assumed_delta)
    opt_t1_price = opt_entry_price + opt_t1_points
    opt_sl_price = max(0.05, opt_entry_price - (opt_t1_points * 0.5))
    opt_be_price = opt_entry_price

    trade = {
        "trade_id": None,  # set by engine
        "trade_date": str(st.date()),
        "execution_mode": str(execution_mode).upper(),
        "status": "OPEN",
        "stage": "FULL_OPEN",   # FULL_OPEN -> HALF_OUT -> CLOSED
        "entry_time_signal": st,
        "entry_time_option": opt_entry_time,
        "side": side,
        "level_tag": level_tag,
        "level_price": level_price,
        "fut_entry": fut_entry,
        "fut_sl": fut_sl,
        "fut_tp": fut_tp,
        "opt_symbol": str(contract_row["tradingsymbol"]),
        "opt_token": int(contract_row["instrument_token"]),
        "opt_expiry": contract_row.get("expiry"),
        "opt_strike": safe_float(contract_row.get("strike")),
        "opt_type": contract_row.get("instrument_type"),
        "opt_lot_size": int(contract_row.get("lot_size", 0)),
        "lots": LOTS,
        "opt_qty": int(max(1, int(contract_row.get("lot_size", 0) or 0) * LOTS)),
        "qty_fraction_open": 1.0,

        "opt_entry_price": opt_entry_price,
        "opt_sl_price": opt_sl_price,
        "opt_t1_price": opt_t1_price,
        "opt_be_price": opt_be_price,

        "exit1_time": None,
        "exit1_price": None,
        "exit2_time": None,
        "exit2_price": None,

        "realized_points_total": 0.0,  # per option point, weighted by fractions
        "gross_pnl_rupees": 0.0,
        "cost_total_rupees": 0.0,
        "net_pnl_rupees": 0.0,
        "close_reason": None,
        "last_update_time": _now_local(),
        "error": None,
        "live_entry_order_id": None,
        "live_exit_order_id": None,
        "live_entry_status": None,
        "live_exit_status": None,
        "live_product": LIVE_PRODUCT,
    }
    return trade


def _points_to_rupees(weighted_points_total: float, lot_size: int, lots: int) -> float:
    return weighted_points_total * lot_size * lots


def _compute_total_costs_rupees(lots: int) -> float:
    # total roundtrip cost for full position (2 lots etc.)
    slippage_total = SLIPPAGE_PER_SIDE_RUPEES * 2 * lots
    charges_total = CHARGES_PER_LOT_ROUNDTRIP * lots
    return slippage_total + charges_total


def _update_trade_from_option_candles(trade: Dict[str, Any], option_candles: pd.DataFrame, now: pd.Timestamp) -> Dict[str, Any]:
    """
    Updates an OPEN trade using all option candles >= entry time up to now.
    Conservative intrabar assumptions when both SL and T1 occur in same candle.
    """
    if trade["status"] != "OPEN":
        return trade

    if option_candles.empty or "date" not in option_candles.columns:
        trade["last_update_time"] = now
        return trade

    df = option_candles.copy()
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)

    entry_time = pd.to_datetime(trade["entry_time_option"], errors="coerce")
    if pd.isna(entry_time):
        trade["error"] = "Invalid entry_time_option"
        trade["last_update_time"] = now
        return trade

    # Process candles after entry time (including entry candle)
    df = df[(df["date"] >= entry_time) & (df["date"] <= now)].copy().reset_index(drop=True)
    if df.empty:
        trade["last_update_time"] = now
        return trade

    entry_price: float = float(trade["opt_entry_price"])
    sl_price: float = float(trade["opt_sl_price"])
    t1_price: float = float(trade["opt_t1_price"])
    be_price: float = float(trade["opt_be_price"])

    stage: str = str(trade["stage"])
    execution_mode = str(trade.get("execution_mode", "PAPER")).upper()
    realized_points_total: float = float(trade["realized_points_total"])
    half: float = 0.5
    rem: float = 0.5

    # If already partially closed, ignore candles before exit1_time
    if stage == "HALF_OUT" and trade.get("exit1_time") is not None:
        exit1_time = pd.to_datetime(trade["exit1_time"], errors="coerce")
        df = df[df["date"] >= exit1_time].copy().reset_index(drop=True)

    for _, row in df.iterrows():
        t = pd.to_datetime(row["date"], errors="coerce")
        h: float = float(row["high"])
        l: float = float(row["low"])

        if stage == "FULL_OPEN":
            sl_hit = l <= sl_price
            t1_hit = h >= t1_price

            if sl_hit and t1_hit:
                # Conservative: assume SL first (worst-case) for full qty
                trade["exit1_time"] = t
                trade["exit1_price"] = sl_price
                trade["exit2_time"] = t
                trade["exit2_price"] = sl_price
                realized_points_total = (sl_price - entry_price) * 1.0 # type: ignore
                trade["status"] = "CLOSED"
                trade["stage"] = "CLOSED"
                trade["close_reason"] = "SL_HIT_AMBIGUOUS_BEFORE_T1"
                break

            if sl_hit:
                trade["exit1_time"] = t
                trade["exit1_price"] = sl_price
                trade["exit2_time"] = t
                trade["exit2_price"] = sl_price
                realized_points_total = (sl_price - entry_price) * 1.0 # type: ignore
                trade["status"] = "CLOSED"
                trade["stage"] = "CLOSED"
                trade["close_reason"] = "SL_HIT"
                break

            if t1_hit:
                if execution_mode == "LIVE":
                    # Live mode uses full-quantity exit on target trigger to keep execution deterministic.
                    trade["exit1_time"] = t
                    trade["exit1_price"] = t1_price
                    trade["exit2_time"] = t
                    trade["exit2_price"] = t1_price
                    realized_points_total = (t1_price - entry_price) * 1.0 # type: ignore
                    trade["status"] = "CLOSED"
                    trade["stage"] = "CLOSED"
                    trade["qty_fraction_open"] = 0.0
                    trade["close_reason"] = "T1_HIT_FULL_LIVE"
                    break
                trade["exit1_time"] = t
                trade["exit1_price"] = t1_price
                realized_points_total += (t1_price - entry_price) * half # type: ignore
                trade["qty_fraction_open"] = rem
                trade["stage"] = "HALF_OUT"
                trade["close_reason"] = "T1_HIT_PARTIAL"
                stage = "HALF_OUT"
                continue

        elif stage == "HALF_OUT":
            be_hit = l <= be_price
            if be_hit:
                trade["exit2_time"] = t
                trade["exit2_price"] = be_price
                realized_points_total += (be_price - entry_price) * rem # type: ignore
                trade["status"] = "CLOSED"
                trade["stage"] = "CLOSED"
                trade["qty_fraction_open"] = 0.0
                trade["close_reason"] = "T1_THEN_BE"
                break

    # Force EOD close if still open and time passed
    force_exit_ts = _today_time(FORCE_EXIT_TIME, now)
    if trade["status"] == "OPEN" and now >= force_exit_ts and not df.empty:
        last = df.iloc[-1]
        last_t = pd.to_datetime(last["date"], errors="coerce")
        last_c = float(last["close"])
        if stage == "FULL_OPEN":
            trade["exit1_time"] = last_t
            trade["exit1_price"] = last_c
            realized_points_total = (last_c - entry_price) * 1.0 # type: ignore
            trade["close_reason"] = "EOD_EXIT_FULL"
        elif stage == "HALF_OUT":
            trade["exit2_time"] = last_t
            trade["exit2_price"] = last_c
            realized_points_total += (last_c - entry_price) * rem # type: ignore
            trade["close_reason"] = "T1_THEN_EOD"
        trade["status"] = "CLOSED"
        trade["stage"] = "CLOSED"
        trade["qty_fraction_open"] = 0.0

    # Recompute PnL
    trade["realized_points_total"] = realized_points_total
    lot_size = int(trade.get("opt_lot_size", 0) or 0)
    gross = _points_to_rupees(realized_points_total, lot_size, int(trade["lots"])) if lot_size > 0 else 0.0
    costs = _compute_total_costs_rupees(int(trade["lots"]))
    trade["gross_pnl_rupees"] = gross
    trade["cost_total_rupees"] = costs
    trade["net_pnl_rupees"] = gross - costs
    trade["last_update_time"] = now

    return trade


# ============================================================
# Logging helpers for signals / trades
# ============================================================
def signal_to_log_row(signal) -> Dict[str, Any]:
    return {
        "logged_at": str(_now_local()),
        "signal_time": str(sig_time(signal)),
        "side": sig_side(signal),
        "level_tag": sig_level_tag(signal),
        "level_price": sig_level_price(signal),
        "fut_entry": sig_entry(signal),
        "fut_sl": sig_sl(signal),
        "fut_tp": sig_tp(signal),
    }


def trade_to_log_row(trade: Dict[str, Any]) -> Dict[str, Any]:
    # flatten timestamps
    row = dict(trade)
    for k in list(row.keys()):
        v = row[k]
        if isinstance(v, (pd.Timestamp, datetime)):
            row[k] = str(v)
    row["logged_at"] = str(_now_local())
    return row


def closed_net_pnl_rupees(closed_trades: List[Dict[str, Any]]) -> float:
    total = 0.0
    for tr in closed_trades:
        total += safe_float(tr.get("net_pnl_rupees"), 0.0) or 0.0
    return float(total)


def flatten_live_trade(kite: KiteConnect, trade: Dict[str, Any]) -> Tuple[bool, str]:
    symbol = str(trade.get("opt_symbol") or "")
    qty = int(trade.get("opt_qty") or 0)
    if not symbol or qty <= 0:
        return False, f"Invalid live flatten payload: symbol={symbol} qty={qty}"

    try:
        oid = place_market_order(
            kite=kite,
            exchange=OPTION_EXCHANGE,
            tradingsymbol=symbol,
            tx_type=kite.TRANSACTION_TYPE_SELL,
            qty=qty,
            product=LIVE_PRODUCT,
        )
        snap = wait_for_order_status(kite, oid, {"COMPLETE", "REJECTED", "CANCELLED"}, LIVE_ORDER_TIMEOUT_SEC)
        status = str((snap or {}).get("status", "UNKNOWN")).upper()
        trade["live_exit_order_id"] = str(oid)
        trade["live_exit_status"] = status
        if status != "COMPLETE":
            return False, f"Exit order not complete. order_id={oid} status={status}"
        return True, f"Exit order complete. order_id={oid}"
    except Exception as e:
        return False, f"Live flatten failed: {e}"


# ============================================================
# Engine state
# ============================================================
class EngineState:
    def __init__(self):
        self.last_completed_candle_time: Optional[pd.Timestamp] = None
        self.seen_signal_times_today: Set[str] = set()
        self.seen_trade_keys_today: Set[str] = set()
        self.trades_today_count: int = 0
        self.open_trades: List[Dict[str, Any]] = []
        self.closed_trades: List[Dict[str, Any]] = []
        self.today_date: Optional[str] = None
        self.loop_count: int = 0

    def reset_for_new_day(self, day_str: str):
        self.last_completed_candle_time = None
        self.seen_signal_times_today.clear()
        self.seen_trade_keys_today.clear()
        self.trades_today_count = 0
        self.open_trades.clear()
        self.closed_trades.clear()
        self.today_date = day_str
        print(f" New trading day state initialized: {day_str}")


# ============================================================
# Main loop
# ============================================================
def main():
    args = _parse_runtime_args()
    profile = args.profile
    execution_mode = str(args.mode).upper()
    apply_strategy_profile(profile)
    if execution_mode == "LIVE" and str(args.confirm).strip() != LIVE_CONFIRM_TEXT:
        raise RuntimeError(f"Live mode blocked. Re-run with: --mode live --confirm {LIVE_CONFIRM_TEXT}")

    print("=" * 80)
    print(f"LIVE RUNNER (ZERODHA) - MODE={execution_mode}")
    print("=" * 80)
    print(f"Profile: {profile}")
    print(
        f"Underlying source: mode={UNDERLYING_SIGNAL_MODE} "
        f"spot={UNDERLYING_SYMBOL} fut_name={UNDERLYING_FUT_NAME} ({UNDERLYING_EXCHANGE}) "
        f"| Options on {OPTION_UNDERLYING_NAME}"
    )
    print(f"Interval: {CANDLE_INTERVAL} | Poll every: {POLL_EVERY_SECONDS}s")
    print(f"Entry window: {ALLOW_ENTRY_FROM} to {ALLOW_ENTRY_TILL} | Force exit: {FORCE_EXIT_TIME}")
    print(f"MAX_TRADES_PER_DAY={MAX_TRADES_PER_DAY} | STOP_FILE={STOP_FILE}")
    print(f"MAX_DAILY_LOSS_RUPEES={MAX_DAILY_LOSS_RUPEES:.2f} | LIVE_PRODUCT={LIVE_PRODUCT}")
    if execution_mode == "LIVE":
        print("WARNING: LIVE mode places REAL ORDERS.")
    print()

    try:
        kite = make_kite()
    except Exception as e:
        log_error("auth", e)
        sys.exit(1)

    try:
        nse_df, nfo_df = load_instruments(kite)
        underlying_token, underlying_label = get_underlying_token(
            nse_df=nse_df,
            nfo_df=nfo_df,
            symbol=UNDERLYING_SYMBOL,
            fut_name=UNDERLYING_FUT_NAME,
            signal_mode=UNDERLYING_SIGNAL_MODE,
        )
        print(f"Underlying token selected: {underlying_token} ({underlying_label})")
    except Exception as e:
        log_error("instrument_setup", e)
        sys.exit(1)

    state = EngineState()

    while True:
        state.loop_count += 1
        now = _now_local()

        # Kill switch
        if os.path.exists(STOP_FILE):
            print(f" STOP file detected ({STOP_FILE}). Exiting runner safely.")
            break

        # Reset state on day change
        day_str = str(now.date())
        if state.today_date != day_str:
            state.reset_for_new_day(day_str)

        # Heartbeat
        if state.loop_count % PRINT_HEARTBEAT_EVERY_LOOPS == 0:
            running_net = closed_net_pnl_rupees(state.closed_trades)
            print(
                f"[{now.strftime('%Y-%m-%d %H:%M:%S %Z')}] heartbeat | "
                f"open={len(state.open_trades)} closed={len(state.closed_trades)} "
                f"trades_today={state.trades_today_count} closed_net={running_net:.2f}"
            )

        # Daily loss kill-switch
        running_net = closed_net_pnl_rupees(state.closed_trades)
        if running_net <= -abs(MAX_DAILY_LOSS_RUPEES):
            print(
                f" Daily loss kill-switch triggered: {running_net:.2f} <= -{abs(MAX_DAILY_LOSS_RUPEES):.2f}. "
                f"No further entries for today."
            )
            if execution_mode == "LIVE" and state.open_trades:
                for tr in state.open_trades:
                    ok, msg = flatten_live_trade(kite, tr)
                    if not ok:
                        log_error("live_kill_switch_flatten", msg, {"trade_id": tr.get("trade_id"), "opt_symbol": tr.get("opt_symbol")})
                    else:
                        print(f" LIVE FLATTEN | {msg}")
            break

        # Outside market hours: just sleep
        if not in_time_window(now, MARKET_START, MARKET_END):
            time.sleep(POLL_EVERY_SECONDS)
            continue

        try:
            # 1) Fetch underlying intraday candles
            raw_df = fetch_underlying_intraday(kite, underlying_token, CANDLE_INTERVAL)
            if raw_df.empty:
                raise RuntimeError("No underlying candles returned.")

            # Ensure required columns exist
            expected_cols = {"datetime", "open", "high", "low", "close"}
            missing = expected_cols - set(raw_df.columns)
            if missing:
                raise RuntimeError(f"Underlying candles missing columns: {missing}. Columns={list(raw_df.columns)}")

            raw_df = raw_df.sort_values("datetime").reset_index(drop=True)

            # 2) Identify latest completed candle (avoid current in-progress candle)
            # For 5m, safest is second last row if latest row may be current.
            if len(raw_df) < 3:
                time.sleep(POLL_EVERY_SECONDS)
                continue

            latest_completed_candle_time = pd.to_datetime(raw_df.iloc[-2]["datetime"], errors="coerce")
            if pd.isna(latest_completed_candle_time):
                raise RuntimeError("Latest completed candle time invalid.")

            # If no new completed candle since last cycle, still update open trades then sleep
            new_candle_available = (
                state.last_completed_candle_time is None
                or latest_completed_candle_time > state.last_completed_candle_time
            )

            # 3) Update open trades every loop (option candles till now)
            if state.open_trades:
                still_open = []
                for tr in state.open_trades:
                    try:
                        opt_token = int(tr["opt_token"])
                        opt_df = fetch_option_intraday_from_signal_time(
                            kite, opt_token, pd.to_datetime(tr["entry_time_signal"], errors="coerce"), interval=CANDLE_INTERVAL
                        )
                        tr = _update_trade_from_option_candles(tr, opt_df, now)
                        if tr["status"] == "CLOSED":
                            if execution_mode == "LIVE" and not tr.get("live_exit_order_id"):
                                ok, msg = flatten_live_trade(kite, tr)
                                if not ok:
                                    tr["error"] = msg
                                    log_error("live_exit_open_trade", msg, {"trade_id": tr.get("trade_id"), "opt_symbol": tr.get("opt_symbol")})
                                else:
                                    print(f" LIVE EXIT | {tr.get('trade_id')} | {msg}")
                            state.closed_trades.append(tr)
                            append_csv_row(TRADES_LOG_CSV, trade_to_log_row(tr))
                            print(
                                f" {execution_mode} TRADE CLOSED | {tr['opt_symbol']} | "
                                f"reason={tr['close_reason']} | net={tr['net_pnl_rupees']:.2f}"
                            )
                        else:
                            still_open.append(tr)
                    except Exception as e:
                        tr["error"] = str(e)
                        log_error("update_open_trade", e, {"trade_id": tr.get("trade_id"), "opt_symbol": tr.get("opt_symbol")})
                        still_open.append(tr)
                state.open_trades = still_open

            if not new_candle_available:
                time.sleep(POLL_EVERY_SECONDS)
                continue

            # Mark processed candle
            state.last_completed_candle_time = latest_completed_candle_time
            print(f"\n New completed candle detected: {latest_completed_candle_time}")

            # 4) Run strategy pipeline on full intraday df (your test_signals logic)
            prepared_df, all_signals = run_strategy_and_capture(raw_df)

            # 5) Filter signals to the latest completed candle only (new ones)
            # We want signals whose entry_time == latest_completed_candle_time
            latest_signals = []
            for s in all_signals:
                st = sig_time(s)
                if pd.isna(st):
                    continue
                if st == latest_completed_candle_time:
                    latest_signals.append(s)

            if not latest_signals:
                print("No new signal on latest completed candle.")
                _debug_latest_candle_no_signal(prepared_df, latest_completed_candle_time)
                time.sleep(POLL_EVERY_SECONDS)
                continue

            print(f"Signals on latest candle: {len(latest_signals)}")

            # 6) Process signals with gating
            for s in latest_signals:
                st = sig_time(s)
                side = sig_side(s)
                fut_entry = sig_entry(s)
                fut_sl = sig_sl(s)
                level_tag = sig_level_tag(s)

                # Time window for entries
                if not in_time_window(now, ALLOW_ENTRY_FROM, ALLOW_ENTRY_TILL):
                    print(f" Signal ignored (outside entry window): {st} {side}")
                    continue

                # Max trades/day
                if state.trades_today_count >= MAX_TRADES_PER_DAY:
                    print(f" Max trades/day reached ({MAX_TRADES_PER_DAY}). Signal ignored.")
                    continue

                # Dedup by signal time
                st_key = str(st)
                if ENABLE_DEDUP_BY_SIGNAL_TIME and st_key in state.seen_signal_times_today:
                    print(f" Duplicate signal-time skipped: {st_key}")
                    continue

                # Dedup by trade key (time+side+level)
                trade_key = f"{st_key}|{side}|{level_tag}|{round(float(fut_entry), 2)}"
                if ENABLE_DEDUP_BY_TRADEKEY and trade_key in state.seen_trade_keys_today:
                    print(f" Duplicate trade-key skipped: {trade_key}")
                    continue

                # Optional: prevent opening multiple simultaneous trades (keep it simple)
                if len(state.open_trades) > 0:
                    print(" Existing open trade present. Skipping new signal (single-position mode).")
                    continue

                # Log signal
                append_csv_row(SIGNALS_LOG_CSV, signal_to_log_row(s))

                # Map option contract
                try:
                    contract_row, err = find_option_contract(
                        nfo_df=nfo_df,
                        signal_time=st,
                        underlying_name=OPTION_UNDERLYING_NAME,
                        side=side,
                        fut_entry_price=fut_entry,
                    )
                    if err or contract_row is None:
                        raise RuntimeError(err or "Option contract mapping failed")

                    option_token = int(contract_row["instrument_token"])
                    option_symbol = str(contract_row["tradingsymbol"])
                    opt_lot_size = int(contract_row.get("lot_size", 0) or 0)
                    if opt_lot_size <= 0:
                        raise RuntimeError(f"Invalid lot_size for {option_symbol}: {opt_lot_size}")
                    opt_qty = int(opt_lot_size * max(1, LOTS))

                    # Fetch option candles for opening
                    opt_df = fetch_option_intraday_from_signal_time(kite, option_token, st, interval=CANDLE_INTERVAL)
                    live_entry_price = None
                    live_entry_time = None
                    live_entry_order_id = None
                    live_entry_status = None

                    if execution_mode == "LIVE":
                        buy_oid = place_market_order(
                            kite=kite,
                            exchange=OPTION_EXCHANGE,
                            tradingsymbol=option_symbol,
                            tx_type=kite.TRANSACTION_TYPE_BUY,
                            qty=opt_qty,
                            product=LIVE_PRODUCT,
                        )
                        buy_snap = wait_for_order_status(kite, buy_oid, {"COMPLETE", "REJECTED", "CANCELLED"}, LIVE_ORDER_TIMEOUT_SEC)
                        buy_status = str((buy_snap or {}).get("status", "UNKNOWN")).upper()
                        if buy_status != "COMPLETE":
                            raise RuntimeError(
                                f"Live entry order not complete: symbol={option_symbol} order_id={buy_oid} status={buy_status}"
                            )
                        quote = kite.quote([f"{OPTION_EXCHANGE}:{option_symbol}"])
                        ltp_fallback = float(quote[f"{OPTION_EXCHANGE}:{option_symbol}"]["last_price"])
                        live_entry_price = _order_avg_fill_price(buy_snap, fallback=ltp_fallback)
                        live_entry_time = _now_local()
                        live_entry_order_id = str(buy_oid)
                        live_entry_status = buy_status

                    trade = open_paper_trade_from_signal(
                        s,
                        contract_row,
                        opt_df,
                        execution_mode=execution_mode,
                        forced_entry_price=live_entry_price,
                        forced_entry_time=live_entry_time,
                    )
                    trade["opt_qty"] = opt_qty
                    trade["live_entry_order_id"] = live_entry_order_id
                    trade["live_entry_status"] = live_entry_status

                    # Assign IDs / mark seen
                    state.trades_today_count += 1
                    trade_id = f"{day_str.replace('-', '')}-{state.trades_today_count:03d}"
                    trade["trade_id"] = trade_id

                    state.seen_signal_times_today.add(st_key)
                    state.seen_trade_keys_today.add(trade_key)

                    # Immediately update once (same loop)
                    trade = _update_trade_from_option_candles(trade, opt_df, now)

                    if trade["status"] == "CLOSED":
                        if execution_mode == "LIVE" and not trade.get("live_exit_order_id"):
                            ok, msg = flatten_live_trade(kite, trade)
                            if not ok:
                                trade["error"] = msg
                                log_error("live_exit_same_loop", msg, {"trade_id": trade.get("trade_id"), "opt_symbol": option_symbol})
                            else:
                                print(f" LIVE EXIT | {trade_id} | {msg}")
                        state.closed_trades.append(trade)
                        append_csv_row(TRADES_LOG_CSV, trade_to_log_row(trade))
                        print(
                            f" {execution_mode} TRADE OPEN+CLOSE | id={trade_id} | {option_symbol} | "
                            f"{side} | reason={trade['close_reason']} | net={trade['net_pnl_rupees']:.2f}"
                        )
                    else:
                        state.open_trades.append(trade)
                        append_csv_row(TRADES_LOG_CSV, trade_to_log_row(trade))
                        print(
                            f" {execution_mode} TRADE OPEN | id={trade_id} | {option_symbol} | {side} | "
                            f"entry={trade['opt_entry_price']:.2f} sl={trade['opt_sl_price']:.2f} t1={trade['opt_t1_price']:.2f}"
                        )

                except Exception as e:
                    log_error(
                        "process_signal",
                        e,
                        {
                            "signal_time": str(st),
                            "side": side,
                            "level_tag": level_tag,
                            "fut_entry": fut_entry,
                            "fut_sl": fut_sl,
                        },
                    )

            # Loop sleep
            time.sleep(POLL_EVERY_SECONDS)

        except KeyboardInterrupt:
            print("\n KeyboardInterrupt received. Exiting.")
            break
        except Exception as e:
            log_error("main_loop", e, {"trace": traceback.format_exc(limit=1)})
            time.sleep(POLL_EVERY_SECONDS)

    # Final summary
    print("\n" + "=" * 80)
    print("Runner stopped.")
    print(f"Closed trades this session: {len(state.closed_trades)}")
    if state.closed_trades:
        dfc = pd.DataFrame([trade_to_log_row(t) for t in state.closed_trades])
        if "net_pnl_rupees" in dfc.columns:
            pnl = pd.to_numeric(dfc["net_pnl_rupees"], errors="coerce").fillna(0)
            print(f"Session paper net PnL: {pnl.sum():,.2f}")
    print("=" * 80)


if __name__ == "__main__":
    main()
